spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  ai:
    openai:
      api-key: ${GOOGLE_AI_API_KEY}
      google-project-id: "my-project-id"
      google-location: "us-central1"
      chat:
        base-url: https://generativelanguage.googleapis.com
        #        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        #        base-url: https://generativelanguage.googleapis.com
        completion-path: /v1beta/models
        model: gemini-1.5-flash
      embedding:
        model: models/gemini-embedding-001

jwt:
  secret: ${JWT_SECRET:1iwoidbaoibdoi2biosfioboiwwfnpadsopnofw}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:3600000}
  cookie:
    secure: ${JWT_COOKIE_SECURE:false}  # 개발환경: false, 운영환경: true
    domain: ${JWT_COOKIE_DOMAIN:localhost}  # 운영환경에서 실제 도메인 예정
    same-site: ${JWT_COOKIE_SAME_SITE:Lax}  # Strict, Lax, None 중 선택 가능

fastapi:
  RECOMMENDATION_FASTAPI_URL: ${RECOMMENDATION_FASTAPI_URL}
  REVIEW_ANALYSIS_FASTAPI_URL: ${REVIEW_ANALYSIS_FASTAPI_URL}
