spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:1iwoidbaoibdoi2biosfioboiwwfnpadsopnofw}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

fastapi:
  RECOMMENDATION_FASTAPI_URL: ${RECOMMENDATION_FASTAPI_URL}
  REVIEW_ANALYSIS_FASTAPI_URL: ${REVIEW_ANALYSIS_FASTAPI_URL}
