spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  ai:
    openai:
      api-key: ${GOOGLE_AI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completion-path: /v1beta/models
        model: gemini-1.5-flash
      embedding:
        options:
          model: text-embedding-ada-002

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  cookie:
    secure: false
    domain: localhost
    same-site: Lax

fastapi:
  RECOMMENDATION_FASTAPI_URL: ${RECOMMENDATION_FASTAPI_URL}
  REVIEW_ANALYSIS_FASTAPI_URL: ${REVIEW_ANALYSIS_FASTAPI_URL}